MAIN_PHOTO_NOT_PLACE = 'AgACAgIAAxkDAAIDyWYPfVQEHFMgb0bDYbwl5regFr1_AAJm4TEbeehQSM2FqniBd-tsAQADAgADdwADNAQ' # фото для старта вне заведения

MAiN_PHOTO_IN_PLACE = 'AgACAgIAAxkDAAIDyWYPfVQEHFMgb0bDYbwl5regFr1_AAJm4TEbeehQSM2FqniBd-tsAQADAgADdwADNAQ' # фото для старта в заведении

# Меню
MAIN_MENU_PHOTO = 'AgACAgIAAxkDAAIDyWYPfVQEHFMgb0bDYbwl5regFr1_AAJm4TEbeehQSM2FqniBd-tsAQADAgADdwADNAQ' # фото главное в меню

# Меню, БЛЮДА
NEW_MENU_PHOTO = 'AgACAgIAAxkDAAIDyWYPfVQEHFMgb0bDYbwl5regFr1_AAJm4TEbeehQSM2FqniBd-tsAQADAgADdwADNAQ' # новинки в меню

BURGERS_MENU_PHOTO = 'AgACAgIAAxkDAAIDyWYPfVQEHFMgb0bDYbwl5regFr1_AAJm4TEbeehQSM2FqniBd-tsAQADAgADdwADNAQ' # бургеры

HOT_DISHES_MENU_PHOTO = 'AgACAgIAAxkDAAIDyWYPfVQEHFMgb0bDYbwl5regFr1_AAJm4TEbeehQSM2FqniBd-tsAQADAgADdwADNAQ' # горячие блюда

HOT_ROLLS_MENU_PHOTO = 'AgACAgIAAxkDAAIDyWYPfVQEHFMgb0bDYbwl5regFr1_AAJm4TEbeehQSM2FqniBd-tsAQADAgADdwADNAQ' # горячие роллы

OPEN_ROLLS_MENU_PHOTO = 'AgACAgIAAxkDAAIDyWYPfVQEHFMgb0bDYbwl5regFr1_AAJm4TEbeehQSM2FqniBd-tsAQADAgADdwADNAQ' # открытые роллы

CLOSSE_ROLLS_MENU_PHOTO = 'AgACAgIAAxkDAAIDyWYPfVQEHFMgb0bDYbwl5regFr1_AAJm4TEbeehQSM2FqniBd-tsAQADAgADdwADNAQ' #  закрытые роллы 

PASTS_MENU_PHOTO = 'AgACAgIAAxkDAAIDyWYPfVQEHFMgb0bDYbwl5regFr1_AAJm4TEbeehQSM2FqniBd-tsAQADAgADdwADNAQ' # пасты 

PIZZS_MENU_PHOTO = 'AgACAgIAAxkDAAIDyWYPfVQEHFMgb0bDYbwl5regFr1_AAJm4TEbeehQSM2FqniBd-tsAQADAgADdwADNAQ' # пиццы 

SALADS_MENU_PHOTO = 'AgACAgIAAxkDAAIDyWYPfVQEHFMgb0bDYbwl5regFr1_AAJm4TEbeehQSM2FqniBd-tsAQADAgADdwADNAQ' # салаты 

SNACKS_MENU_PHOTO = 'AgACAgIAAxkDAAIDyWYPfVQEHFMgb0bDYbwl5regFr1_AAJm4TEbeehQSM2FqniBd-tsAQADAgADdwADNAQ' # закуски 

SLICES_MENU_PHOTO = 'AgACAgIAAxkDAAIDyWYPfVQEHFMgb0bDYbwl5regFr1_AAJm4TEbeehQSM2FqniBd-tsAQADAgADdwADNAQ' # нарезки

SOUS_MENU_PHOTO = 'AgACAgIAAxkDAAIDyWYPfVQEHFMgb0bDYbwl5regFr1_AAJm4TEbeehQSM2FqniBd-tsAQADAgADdwADNAQ' # соусы

#Бронирование
MAIN_BOOKING_PHOTO = 'AgACAgIAAxkDAAIDyWYPfVQEHFMgb0bDYbwl5regFr1_AAJm4TEbeehQSM2FqniBd-tsAQADAgADdwADNAQ'  # фото главное в бронировании

# Заказ 
MAIN_ORDER_PHOTO = 'AgACAgIAAxkDAAIDyWYPfVQEHFMgb0bDYbwl5regFr1_AAJm4TEbeehQSM2FqniBd-tsAQADAgADdwADNAQ'  # фото главное в заказе
